name: Sushi - apps / evm

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/apps-evm-e2e.yml"
      - "apps/evm/**"
      - "config/nextjs/**"
      - "config/react-query/**"
      - "config/router/**"
      - "config/tailwindcss/**"
      - "config/typescript/**"
      - "config/viem/**"
      - "config/wagmi/**"
      - "packages/**"

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./apps/evm

# https://playwright.dev/docs/ci#sharding
env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NODE_OPTIONS: --max-old-space-size=8192
  NEXT_TELEMETRY_DISABLED: 1
  EDGE_CONFIG: ${{ secrets.EDGE_CONFIG }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain-id: [137]
        dst-chain-id: [42161]
        node-version: [18]
        pnpm-version: [8.9.2]
        block-number: [47479278]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: .
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Install playwright
        run: npx playwright install --with-deps chromium

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Test
        run: pnpm exec turbo run test --filter evm
        env:
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
          ANVIL_BLOCK_NUMBER: ${{ matrix.block-number }}
          ANVIL_PORT: 8545
          NEXT_PUBLIC_ALCHEMY_ID: ${{ secrets.NEXT_PUBLIC_ALCHEMY_ID }}
          NEXT_PUBLIC_CHAIN_ID: ${{ matrix.chain-id }}
          # NEXT_PUBLIC_DST_CHAIN_ID: ${{ matrix.dst-chain-id }}
          # NEXT_PUBLIC_DRPC_ID: ${{ secrets.NEXT_PUBLIC_DRPC_ID }}
        working-directory: .

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./apps/evm/test-results/